markdown: rdiscount
name: Pawel Duda
title: Pawel Duda
author: Pawel Duda
description: Pawel's blog
url: http://unclejamal.github.io
baseurl: "" # the subpath of your site, e.g. /blog/

excerpt_separator: "" # workaround for broken code excerpts: http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
